name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # You can specify the Node.js version you need
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod

      # - name: Linting TypeScript
      #   run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

      - name: Unit Testing
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      # - name: Screenshot Testing
      #   run: npm run test:ui:ci
